### ISSUE TITLE
Not-so-nice display in mobile (Redmi Note 3 Pro)

### ISSUE THREAD

**Issue by solidx86** [heiniha/Nagios-Responsive-HTML-Email-Notifications#1]
Hi @heiniha, first of all, thank you for your work, love it!

However in my mobile, it doesn't look as nice as on PC/Laptop. I'm not a web UI designer/developer, i wish i can help to fix that =(
![nagios_email_mobile_screenshot](https://user-images.githubusercontent.com/1960463/29483526-e6583b7e-84da-11e7-813d-996b63f2b522.png)

**Comment by heiniha** [comment]
Hi @acefreakz and thanks for helping me figure out issues with the scripts, I'll try and see if I can fix them soonest possible, but please give me some time, because I think that I will need to re-code and re-write many things in order to be able to support all email clients.

Regards,
@heiniha

**Comment by solidx86** [comment]
hey @heiniha , sure no problem! Appreciate the effort :) btw my 'workaround' at the mean time is to rotate my screen (on my mobile) when i'm checking out the notifications from Nagios haha!

**Comment by solidx86** [comment]
Hi @heiniha, here're some screenshots for your reference. Some're working, some're not.

![screenshot_2017-08-23-13-12-00-931_com google android gm](https://user-images.githubusercontent.com/1960463/29625524-8e6e0a42-885e-11e7-811a-97f6f9541d9e.png)
![screenshot_2017-08-23-21-19-38-191_com google android gm](https://user-images.githubusercontent.com/1960463/29625525-8e6e9f52-885e-11e7-8703-d40a7dc0cbed.png)
![screenshot_2017-08-23-21-19-48-571_com google android gm](https://user-images.githubusercontent.com/1960463/29625523-8e6c0062-885e-11e7-9a9e-aa97a9c75afa.png)
![screenshot_2017-08-23-21-22-13-594_com google android gm](https://user-images.githubusercontent.com/1960463/29625526-8e706468-885e-11e7-853a-f4a0e81ef571.png)

**Comment by heiniha** [comment]
Hi @acefreakz,
I've now managed to update the scripts (html and css) and I've done some small modifications to, but it should now be working, I've tested it a lot, but please can you test the new versions as well and let me know if all is okay now?

Regards,
Heini

**Comment by heiniha** [comment]
Hi @acefreakz,

Any news on whether you are facing issues with the updated files, or not?

Looking very much forward to hear back from you.


- @heiniha

**Comment by heiniha** [comment]
Hi @acefreakz,

Have you been able to test the updated scripts?
Please let me know if it has solved you're display problems?

Thanks in advance.

**Comment by heiniha** [comment]
Due to intensive testing, where layout seems to be just fine in all tested email clients, i'm going to close this issue and mark it as solved.
